[package]
name = "intiface-cli"
version = "101.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Command Line Interface frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-cli-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2021"
exclude = [".vscode/**"]

[dependencies]
# buttplug = { path = "../buttplug-rs/buttplug" }
buttplug = "5.1.10"
argh = "0.1.8"
log = "0.4.17"
futures = "0.3.21"
tracing-fmt = "0.1.1"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "json"] }
tracing = "0.1.35"
tokio = { version = "1.20.0", features = ["sync", "rt-multi-thread", "macros", "io-std", "fs", "signal", "io-util"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
backtrace = "0.3.66"
ctrlc = "3.2.2"
tokio-util = "0.7.3"
serde = "1.0.139"
serde_json = "1.0.82"
sentry = "0.27.0"
sentry-tracing = "0.27.0"
async-tungstenite = "0.17.2"
thiserror = "1.0.31"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[build-dependencies]
vergen = "7.2.1"
anyhow = "1.0.58"

[patch.crates-io]

# If you want to use the bleeding edge version of `egui`:
sentry = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }
sentry-tracing = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# eframe = { path = "../egui/eframe" }
