[package]
name = "intiface-cli"
version = "40.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Command Line Interface frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-cli-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"
exclude = [".vscode/**"]

[dependencies]
buttplug = { path = "../buttplug-rs/buttplug" }
# buttplug = "5.0.1"
argh = "0.1.6"
log = "0.4.14"
futures = "0.3.17"
tracing-fmt = "0.1.1"
tracing-subscriber = { version = "0.3.2", features = ["env-filter", "json"] }
tracing = "0.1.29"
tokio = { version = "1.14.0", features = ["sync", "rt-multi-thread", "macros", "io-std", "fs", "signal", "io-util", "net"] }
log-panics = { version = "2.0.0", features = ["with-backtrace"] }
backtrace = "0.3.63"
ctrlc = "3.2.1"
tokio-util = "0.6.9"
serde = "1.0.130"
serde_json = "1.0.68"
sentry = "0.23.0"
sentry-tracing = "0.23.0"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3.9"

[build-dependencies]
vergen = "5.1.15"
anyhow = "1.0.44"

[patch.crates-io]

# If you want to use the bleeding edge version of `egui`:
sentry = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }
sentry-tracing = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# eframe = { path = "../egui/eframe" }
